function [ rotation_matrix_Kardan ] = R_Kardan( a,b,c )
%Rotation matrix using Kardan angles phi_x, phi_y,phi_z

rotation_matrix_Kardan=[cos(b)*cos(c) -cos(b)*sin(c) sin(b);...
    cos(a)*sin(c)+sin(a)*sin(b)*sin(c) ...
    cos(a)*cos(c)-sin(a)*sin(b)*sin(c) -sin(a)*cos(b);...
    sin(a)*sin(c)-cos(a)*sin(b)*cos(c) ...
    sin(a)*cos(c)+cos(a)*sin(b)*sin(c) cos(a)*cos(b)];


end

